server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://0.0.0.0:5432/productdb
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: PRODUCT-SERVICE
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}